modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Nero"
logoFile="icon.png"
description='''
This mod will add one mechanic from the old alpha versions of minecraft. hit the sheep so that it sheds its wool.
'''
[[dependencies."${mod_id}"]]
   modId="forge"
   mandatory=true #mandatory
   versionRange="[47.3.0,)"
   ordering="NONE"
   side="SERVER"
[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.20.4]"
   ordering="NONE"
   side="SERVER"
